services:
  bunkoshelf:
    image: itsmrtr/bunkoshelf:latest
    container_name: bunkoshelf
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5050:3000" # Cambia 5050 por otro puerto si ya está en uso
    volumes:
      - ./data:/app/data
      - ./path/to/your/books:/app/library # Biblioteca donde tengas tus libros
    environment:
      - NODE_ENV=production
    restart: unless-stopped
